# Generated by Django 3.2.13 on 2022-08-03 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lionel Messi', max_length=255, verbose_name='Username')),
                ('email', models.EmailField(max_length=225)),
                ('birth_date', models.DateField(default='2007-09-12', verbose_name='Born')),
                ('gender', models.CharField(choices=[('m', 'Boy'), ('f', 'Girl')], default='', max_length=1, verbose_name='Sex')),
                ('location', models.CharField(default='Panfilov 188', max_length=120, verbose_name='Address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_set', to='blog.categories')),
            ],
        ),
    ]
